bin/bar2vtk.py
Adding information regarding the creation of time windows in the help output of the `bar2vtk` utility.
=> doc: Add time window information to bar2vtk --help

example/makeVTM.py, vtkpytools/bar2vtk/core.py
Move form2DGrid to use array inputs instead of paths. This makes it more flexible in terms of reading in different files and formats.
=> feat: Move form2DGrid to use array inputs

bin/bar2vtk.py
- When symlinked, `bar2vtk` would not reference the correct path for the `vtkpytools` repository.
=> Fix bar2vtk path resolving

bin/bar2vtk.py
Changes in `velbarPaths` structure weren't reflected in the print statements in the timestep window ranges.
=> fix(bar2vtk): Correct changes in velbarPaths

vtkpytools/bar2vtk/__init__.py, vtkpytools/bar2vtk/data.py
- Cf calculation used wrong definition for du/dn
- Calculation of du/dn now done in calcWallShearGradient
Derivation of the (new) method for calculating wall shear gradient is found at [my website](https://www.jameswright.xyz/post/wall_shear_gradient_from_velocity_gradient/).
=> fix: Fix Cf calculation, add calcWallShearGradient

vtkpytools/bar2vtk/data.py
- Allow overriding the wall normal value
- Useful for cases when the `Normals` located on the `wall` would make the profile exit the domain
=> feat: Add custom normal option for sampleDataBlockProfile

bin/bar2vtk.py
Previous glob string wasn't strict enough, so it needed replacing.
While at it, I added the `--velbar` and `--stsbar` flags to `bar2vtk` to allow for explicit selection of the paths to each respective files. They also allow for two files to be given in the case of creating split time windows.
=> Feat: Better barfile selection in bar2vtk

bin/bar2vtk.py
Add error check for the new `--velbar` and `--stsbar` flags.
- If given two paths, but timestep isn't a range, return error
Then refactored error code into a for loop.
=> Refactor: bar2vtk with error checks

vtkpytools/barfiletools/data.py, vtkpytools/common.py
Rotating a rank 2 tensor resulted in incorrect data. Was incidentally computing:
instead of
where **a** is the rotation tensor and **R** is the rank 2 tensor to be rotated.
=> Fix: Rotate tensor

vtkpytools/barfiletools/data.py
Originally, `sampleDataBlockProfile` checked whether `pointid` was given as an argument was tested via the variables ["truthiness"](https://stackoverflow.com/questions/39983695/what-is-truthy-and-falsy-how-is-it-different-from-true-and-false). Thus, it would fail if it was 0. 
Changed to using `isinstance(pointid, int)` instead to be more strict and not fail unexpectedly.
=> fix(barfiletools): pointid truthiness fixed

vtkpytools/common.py
Replace the `.flatten()` with `.reshape(n,9)` when given an `[n,9]` shaped array.
=> fix: rotateTensor output 2D array when given [n,9] shape

vtkpytools/common.py
Make the endpoint of the series be the max value passed to the function. Provides a more consistent result.
=> fix(getGeometricSeries): Force endpoint to be max value

bin/bar2vtk.py
- Previous calculation of turbulent kinetic energy was incorrect (using 1/3 instead of 1/2)
- Calculation removed entirely to:
1. Minimize dependencies in the code (ie. trust the user more than the programmer)
2. Allow easy way to determine if loaded vtm file has correct/incorrect TKE calcuation (ie. if it has a 'TurbulentEnergyKinetic' array, then it is the wrong calculation).
3. Reduce file size of the loaded vtm file (not overly significant, but a pro nonetheless)
=> fix(bar2vtk): Remove incorrect TKE calculation

bin/bar2vtk.py, example/bar2vtk/runbar2vtk.sh, setup.py, vtkpytools/barfiletools/__init__.py, vtkpytools/barfiletools/bar2vtk.py
Use [`toml` documents](https://toml.io/en/) as configuration files for `bar2vtk` and as "receipt" files to keep track of how a file was created. Todo:
Closes #34
=> feat(bar2vtk): Add toml support

vtkpytools/_version.py
Give the `master` branch the `dev0` designation to differentiate it from an official release.
Will be particularly important with the addition of the toml receipt files, as they actually keep track of the vtkpytools version they were created with.
=> chore: Change version number for master branch

tests/test_common.py, vtkpytools/barfiletools/bar2vtk.py, vtkpytools/common.py
Allow for python regex strings to be used in `globFile` via the `regex` keyword argument (ie. `globfile(r'.*', Path('.'), regex=True)`).
- Added appropriate tests to check it
- Closes #47
=> feat: Add regex capability to globFile, bar2vtk

tests/barfiletools/test_bar2vtk.py, vtkpytools/barfiletools/bar2vtk.py
- Previous version left of the `regex=True` flag when calling `globFile()`.
- Also, for non-timestep windows, regex globing would not have worked
- Added explicit test for bar2vtk globing
- ie. `velbar.10000` and `velbar.100000` should be differentiated and not error out
=> fix(bar2vtk): Fully implement bar2vtk regex globing

vtkpytools/barfiletools/bar2vtk.py, vtkpytools/barfiletools/data.py, vtkpytools/gridtools2d/core.py
- Newer versions of pyvista check that `size(offset) == size(cellArray)`,
which was off by one (but had no consequences actual consequences)
- Replaced the `compute_gradient` method with `compute_derivative` that I contributed (https://github.com/pyvista/pyvista/pull/837)
- Also replaces (and thus deprecates) `vpt.compute_vorticity`
=> fix: Correct offset in gridtools2d, use `compute_derivative`

vtkpytools/barfiletools/bar2vtk.py, vtkpytools/barfiletools/data.py
Allow for stsbar files using conservative stress to be imported and used in `bar2vtk`.
Conservative stress stsbar files are structured as:
```
<u> <v> <w> <uu> <vv> <ww> <uv> <uw> <vw>
```
where all quantities are the "conserved" versions.
=> feat(bar2vtk): Conservative stresses implemented for bar2vtk

tests/test_numtools.py, vtkpytools/numtools.py
`symmetric2FullTensor` and `full2SymmetricTensor` were changed by:
- Adding a input check to verify that the incoming array was of size `(...,6)` or `(...3,3)`, respectively
- Add ability for the input array to have arbitrary leading dimensionality.
- 	So an array of shape `(10,100,6)` could be input and transformed to `(10,100,3,3)`
- Added tests to verify all the above changes.
=> feat(numtools): sym<->full input check, `...` ability

vtkpytools/common.py, vtkpytools/gridtools2d/core.py, vtkpytools/numtools.py
- That version deprecated the `*.{point,cell}_arrays` in favor of `*.{point,cell}_data`
- Also fixes for deprecated numpy datatypes `np.int` and `np.float`
=> fix: Update for pyvista >0.37.0
